import org.elasticsearch.plugin.sample.*

class BootStrap {

    def init = { servletContext ->

      def location1 = new Location(lat: -46.22159, lon:114.02504, name: "Lorem ipsum dolor.")
      location1.save()
      def location2 = new Location(lat: 46.26095, lon:-61.20178, name: "Lorem ipsum dolor.")
      location2.save()
      def location3 = new Location(lat: -11.35155, lon:-105.31714, name: "Lorem ipsum dolor.")
      location3.save()
      def location4 = new Location(lat: 61.71088, lon:-115.05247, name: "Lorem ipsum dolor.")
      location4.save()
      def location5 = new Location(lat: -21.81039, lon:113.24358, name: "Lorem ipsum dolor.")
      location5.save()
      def location6 = new Location(lat: 43.17282, lon:166.72582, name: "Lorem ipsum dolor.")
      location6.save()
      def location7 = new Location(lat: -15.00147, lon:-23.41309, name: "Lorem ipsum dolor.")
      location7.save()
      def location8 = new Location(lat: -61.28267, lon:53.26881, name: "Lorem ipsum dolor.")
      location8.save()
      def location9 = new Location(lat: 15.06730, lon:94.27362, name: "Lorem ipsum dolor.")
      location9.save()
      def location10 = new Location(lat: -36.20142, lon:-112.50900, name: "Lorem ipsum dolor.")
      location10.save()
      def location11 = new Location(lat: 14.04404, lon:131.85006, name: "Lorem ipsum dolor.")
      location11.save()
      def location12 = new Location(lat: -23.71282, lon:25.65946, name: "Lorem ipsum dolor.")
      location12.save()
      def location13 = new Location(lat: 19.73471, lon:-75.78112, name: "Lorem ipsum dolor.")
      location13.save()
      def location14 = new Location(lat: 24.53290, lon:-86.54211, name: "Lorem ipsum dolor.")
      location14.save()
      def location15 = new Location(lat: 34.60722, lon:66.02620, name: "Lorem ipsum dolor.")
      location15.save()
      def location16 = new Location(lat: 57.90852, lon:-121.78965, name: "Lorem ipsum dolor.")
      location16.save()
      def location17 = new Location(lat: -12.73043, lon:-148.32959, name: "Lorem ipsum dolor.")
      location17.save()
      def location18 = new Location(lat: 19.29111, lon:161.42981, name: "Lorem ipsum dolor.")
      location18.save()
      def location19 = new Location(lat: 51.24864, lon:-57.31104, name: "Lorem ipsum dolor.")
      location19.save()
      def location20 = new Location(lat: 76.51164, lon:-12.25289, name: "Lorem ipsum dolor.")
      location20.save()
      def location21 = new Location(lat: null, lon:86.43618, name: "Lorem ipsum dolor.")
      location21.save()


      def parent1 = new Musician(firstName: 'Jim', lastName: 'Morrison', age:42, locationBorn: location1)
      parent1.save()
      def parent2 = new Musician(firstName: 'Jimmy', lastName: 'Hendrix', age:40, locationBorn: location2)
      parent2.save()
      def parent3 = new Musician(firstName: 'Lou', lastName: 'Reed', age:51, locationBorn: location3)
      parent3.save()
      def parent4 = new Musician(firstName: 'Jimmy', lastName: 'Page', age:57, locationBorn: location4)
      parent4.save()
      def parent5 = new Musician(firstName: 'David', lastName: 'Gilmour', age:63, locationBorn: location5)
      parent5.save()
      def parent6 = new Musician(firstName: 'Roger', lastName: 'Waters', age:65, locationBorn: location5)
      parent6.save()

      def song1 = new Song(title: "All Along the Watchtower", dateWritten: new Date())
      song1.save()
      def song2 = new Song(title: "Hey Joe", dateWritten: new Date())
      song2.save()
      def song3 = new Song(title: "Riders on the storm", dateWritten: new Date())
      song3.save()
      def song4 = new Song(title: "The end", dateWritten: new Date())
      song4.save()
      def song5 = new Song(title: "People Are Strange", dateWritten: new Date())
      song5.save()
      def song6 = new Song(title: "Sweet Jane", dateWritten: new Date())
      song6.save()
      def song7 = new Song(title: "Stairway to Heaven", dateWritten: new Date())
      song7.save()
      def song8 = new Song(title: "Comfortably Numb", dateWritten: new Date())
      song8.save()
      def song9 = new Song(title: "Another Brick in the Wall", dateWritten: new Date())
      song9.save()
      def song10 = new Song(title: "I Feel Love", dateWritten: new Date())
      song10.save()

      parent1.addToSong(song10).save()
      parent1.addToSong(song3).save()
      parent1.addToSong(song4).save()
      parent1.addToSong(song5).save()
      parent2.addToSong(song1).save()
      parent2.addToSong(song2).save()
      parent3.addToSong(song6).save()
      parent4.addToSong(song7).save()
      parent5.addToSong(song8).save()
      parent5.addToSong(song9).save()

      parent1.addToLocationPlayed(location1).save()
      parent2.addToLocationPlayed(location2).save()
      parent3.addToLocationPlayed(location3).save()
      parent4.addToLocationPlayed(location4).save()
      parent5.addToLocationPlayed(location5).save()
      parent4.addToLocationPlayed(location6).save()
      parent3.addToLocationPlayed(location7).save()
      parent2.addToLocationPlayed(location8).save()
      parent1.addToLocationPlayed(location9).save()
      parent2.addToLocationPlayed(location10).save()
      parent3.addToLocationPlayed(location11).save()

      song1.addToLocationPlayed(location1)
      song1.save()
      song1.addToLocationPlayed(location10)
      song1.save()
      song2.addToLocationPlayed(location2)
      song2.save()
      song2.addToLocationPlayed(location11)
      song2.save()
      song3.addToLocationPlayed(location3)
      song3.save()
      song3.addToLocationPlayed(location12)
      song3.save()
      song4.addToLocationPlayed(location4)
      song4.save()
      song4.addToLocationPlayed(location13)
      song4.save()
      song5.addToLocationPlayed(location5)
      song5.save()
      song5.addToLocationPlayed(location14)
      song5.save()
      song6.addToLocationPlayed(location6)
      song6.save()
      song6.addToLocationPlayed(location15)
      song6.save()
      song7.addToLocationPlayed(location7)
      song7.save()
      song7.addToLocationPlayed(location16)
      song7.save()
      song8.addToLocationPlayed(location8)
      song8.save()
      song8.addToLocationPlayed(location17)
      song8.save()
      song9.addToLocationPlayed(location9)
      song9.save()
      song9.addToLocationPlayed(location18)
      song9.save()
    }
    def destroy = {
    }
}
